# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 海阔天空 BLOG 
email: zsszsszsszss@126.com 
description: > # this means to ignore newlines until "baseurl:"
  ShengShan Zhagn, zsszsszsszss@126.com
baseurl: "/MyBlog" # the subpath of your site, e.g. /blog
url: "http://zhangshengshan.github.io/MyBlog" # the base hostname & protocol for your site
twitter_username: NULL 
github_username:  zhangshengshan 

# Build settings
markdown: kramdown
